# Generated by Django 2.0 on 2021-02-03 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_census_adscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='census',
            name='adscripcion',
        ),
    ]
